name: Docs CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm --filter docs lint

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run Tests
        run: pnpm --filter docs test:ember

  fastboot-test:
    name: "Fastboot Tests"
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
          
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run Tests
        run: pnpm --filter docs test:fastboot